language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before-script:
   - composer self-update
script:
   - php composer.phar install
   - phpunit -c ./phpunit.xml src/
   - php bin/behat