# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |configManager|

  # Every Vagrant virtual environment requires a box to build off of.
  configManager.vm.box = "ubuntu/trusty64"

  # Create a private network, which allows host-only access to the machine using a specific IP.
  configManager.vm.network "private_network", ip: "192.168.33.22", type: "nfs"

  # Share an additional folder to the guest VM. The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  configManager.vm.synced_folder "./../", "/var/www/research_gate"

  configManager.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
  configManager.vm.provision :shell, path: "provision.sh"

end