Feature:
  In order to count the word occurrences in different stream
  As as console user
  I need a command that consume a source text stream and return a list odored by count and occurrence name

  Scenario: retrieve word occurrences from an internal file source
    Given there is a "small_text.txt" in my system
    When the command "php /../../bin/word_count.php"
    Then the result would be equal to:
    """
    {
      "mozart": 7,
      "from": 4,
      "the": 3,
      "and": 3,
      "wolfgang": 2,
      "see": 2,
      "of": 2,
      "amadeus": 2,
      "a": 2,
      "wolfgangus": 1,
      "wikipedia": 1,
      "was": 1,
      "violin": 1,
      "v": 1,
      "uses": 1,
      "tsa": 1,
      "theophilus": 1,
      "t": 1,
      "showed": 1,
      "semi": 1,
      "salzburg": 1,
      "s": 1,
      "royalty": 1,
      "redirects": 1,
      "protected": 1,
      "prolific": 1,
      "prodigious": 1,
      "portrait": 1,
      "performed": 1,
      "page": 1,
      "other": 1,
      "on": 1,
      "nepomuk": 1,
      "mo": 1,
      "lf": 1,
      "keyboard": 1,
      "johannes": 1,
      "johann": 1,
      "january": 1,
      "influential": 1,
      "in": 1,
      "his": 1,
      "here": 1,
      "he": 1,
      "german": 1,
      "free": 1,
      "for": 1,
      "fn": 1,
      "five": 1,
      "european": 1,
      "era": 1,
      "english": 1,
      "encyclopedia": 1,
      "earliest": 1,
      "disambiguation": 1,
      "detail": 1,
      "della": 1,
      "december": 1,
      "de": 1,
      "croce": 1,
      "composer": 1,
      "composed": 1,
      "competent": 1,
      "classical": 1,
      "chrysostomus": 1,
      "childhood": 1,
      "c": 1,
      "by": 1,
      "born": 1,
      "before": 1,
      "baptised": 1,
      "as": 1,
      "ama": 1,
      "already": 1,
      "age": 1,
      "ability": 1
    }
    """
